### ISSUE TITLE
Não está sendo criado o mock com queryParams

### ISSUE THREAD

**Issue by jorgejlp91** [osvaldjr/easy-cucumber#1]
Fiz as devidas configurações e não está sendo criado o mock com a tag queryParans.

application.yml:

   ```yaml
target.url: http://localhost:8080/api/v1
dependencies:
  stubby.url: http://localhost:8905
```

request.json:

```json
{
  "url": "/search/*",
  "method": "GET",
  "body": {
    "id": 123456
  },
  "headers": {
    "content-type": "application/json"
  },
  "queryParams": {"name": "tenis"}
}
```
